### GET request to the root path of the server
GET localhost:8080

### GET request to retrieve all users
GET localhost:8080/api/v1/users

### POST request to add a new user
POST localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "nasser",
  "email": "basha312r@example.com",
  "phone": "0551234567",
  "height": 175,
  "weight": 75,
  "password": "MySecretPassword123",
  "emergencyEnabled": true,
  "emergencyContacts": [
    {
      "name": "Ali Friend",
      "phone": "0559998888"
    },
    {
      "name": "Sara Sister",
      "phone": "0557776666"
    }
  ]
}

### GET request to retrieve a user by ID
GET localhost:8080/api/v1/users/1

### DELETE request to delete a user by ID
DELETE localhost:8080/api/v1/users/4

### PUT request to update a user by ID
PUT localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "name": "Bashar upldate 1",
  "email": "basha444@retmaam.com.sa",
  "phone": "0500061559",
  "height": 180,
  "weight": 78,
  "password": "NewPassword123",
  "emergencyEnabled": true,
  "emergencyContacts": [
    {
      "id": 1,
      "name": "update ali",
      "phone": "0559991111"
    },
    {
      "name": "fourth one new",
      "phone": "0500000000"
    }
  ]
}

### PUT request to register a new user (path might be incorrect for login)
PUT localhost:8080/api/v1/registration
Content-Type: application/json

{
  "name": "Bashar upldate 1",
  "email": "fasfasf@gmail.com",
  "password": "ASFakf24!%!%22"
}
