spring.application.name=IoT
spring.datasource.url=jdbc:postgresql://localhost:5332/iot
spring.datasource.username=IotUser
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

##docker exec -it postgres-spring-boot bash
## psql -U IotUser
## \c iot
## \d users
## SELECT * FROM USERS;
