# Server port (unique per microservice)
server.port=8084

# Service name
spring.application.name=health-data-service

# Database Configuration
spring.datasource.url=jdbc:sqlite:health_data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Queue Names
app.queue.measurement=measurement.queue

# Enable AMQP
spring.rabbitmq.template.mandatory=true

